######################################################################
# Automatically generated by qmake (3.0) mer. 17. juil. 11:14:22 2013
######################################################################

TEMPLATE = lib
TARGET = jp2
INCLUDEPATH += ../include

CONFIG += staticlib

DESTDIR = ../../build

# Input
HEADERS += jp2_cod.h jp2_dec.h
SOURCES += jp2_cod.c jp2_dec.c jp2_enc.c
