######################################################################
# Automatically generated by qmake (2.01a) ven. 3. avr. 19:48:20 2009
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += mainwindow.h
SOURCES += main.cpp maiwindow.cpp
