/**********************************************************************
qtVlm: Virtual Loup de mer GUI
Copyright (C) 2013 - Christophe Thomas aka Oxygen77

http://qtvlm.sf.net

This program is free software: you can redistribute it and/or modify
it under the terms of the GNU General Public License as published by
the Free Software Foundation, either version 3 of the License, or
(at your option) any later version.

This program is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
GNU General Public License for more details.

You should have received a copy of the GNU General Public License
along with this program.  If not, see <http://www.gnu.org/licenses/>.

***********************************************************************/

#ifndef SETTINGS_DEF_H
#define SETTINGS_DEF_H

enum { // for new setting always add at the end in order to preserve compatibility with old version
    defaultFontName,
    applicationFontSize,
    defaultFontSizeInc,
    appLanguage,
    enable_Gesture,
    forceUserAgent,
    userAgent,
    saveMainWindowGeometry,
    show_DashBoard,
    projectionCX,
    projectionCY,
    projectionScale,
    mainWindowSize,
    mainWindowPos,
    mainWindowMaximized,
    qtVlm_version,
    savedState,

    gpsEmulEnable,
    gpsEmulSerialName,
    gpsEmulDelay,

    boardVLMCompassShown,
    defaultSkin,
    fusionStyle,
    vlmBoardType,
    newBoard_Shadow,

    defaultGribDwnld,

    estimeType,
    estimeTime,
    estimeVac,
    estimeLen,
    startSpeedEstime,

    compassCenterBoat,
    scalePolar,

    magnifierZoom,
    magnifierSize,

    keepBoatPosOnScreen,
    LastBoatSelected,

    askConfirmation,
    opp_labelType,
    centerOnSynch,
    centerOnBoatChange,
    traceLength,
    vlm_url,
    opp_trace,
    speed_replay,

    polar_efficiency,
    boat_declinaison,
    boat_minSpeedForEngine,
    boat_speedWithEngine,

    isobarsStepSet,
    isoTherms0StepSet,
    force_Wind,
    forced_TWS,
    forced_TWD,
    force_Currents,
    forced_CS,
    forced_CD,
    colorMapSmoothSet,
    showBarbulesSet,
    frstArrowColor,
    secArrowColor,
    labelColor,
    showPressureMinMaxSet,
    showIsobarsSet,
    showIsobarsLabelsSet,
    showIsotherms0Set,
    isotherms0StepSet,
    showIsotherms0LabelsSet,
    gribDrawingMethod,
    gribBench1,
    gribBench2,
    gribMonoCpu,
    cloudsColorMode,
    gribDateStep,
    isoBar_levelType,
    isoBar_levelValue,
    colorMap_mode,
    colorMap_levelType,
    colorMap_levelValue,
    frstArw_mode,
    frstArw_levelType,
    frstArw_levelValue,
    secArw_mode,
    secArw_levelType,
    secArw_levelValue,
    label_mode,
    label_levelType,
    label_levelValue,
    gribZoomOnLoad,
    gribDelete,
    defaultInterpolation,
    grib_FileName,
    gribCurrent_FileName,
    showGribInfoAfterLoad,

    sDocExternalMail,
    sailsDoc_press,

    downloadGribResolution,
    downloadGribInterval,
    downloadGribNbDays,
    downloadWind,
    downloadPressure,
    downloadRain,
    downloadCloud,
    downloadTemp,
    downloadHumid,
    downloadIsotherm0,
    downloadTempPot,
    downloadTempMin,
    downloadTempMax,
    downloadSnowCateg,
    downloadFrzRainCateg,
    downloadCAPEsfc,
    downloadCINsfc,
    downloadAltitudeData200,
    downloadAltitudeData300,
    downloadAltitudeData500,
    downloadAltitudeData700,
    downloadAltitudeData850,

    edtGribFolder,
    askGribFolder,
    mapsFolderName,
    logsFolder,
    faxPathFolder,
    kapMapPath,
    exportRouteCSVFolder,
    gribFile_Path,
    screenShotFolder,
    importRouteFolder,

    KeepOldPoi,

    backgroundColor,
    seaColor,
    landColor,
    landOpacity,
    nightOpacity,
    estimeLineWidth,
    estimeLineColor,
    seaBordersLineWidth,
    seaBordersLineColor,
    boundariesLineWidth,
    boundariesLineColor,
    riversLineWidth,
    riversLineColor,
    isobarsLineWidth,
    isobarsLineColor,
    isotherms0LineColor,
    isotherms0LineWidth,
    nextGateLineWidth,
    nextGateLineColor,
    gateLineWidth,
    gateLineColor,
    routeLineWidth,
    routeLineColor,
    traceLineWidth,
    traceLineColor,
    POIColor,
    MarqueWPColor,
    qtBoatColor,
    qtBoatSelColor,
    WPColor,
    BaliseColor,
    show_countriesBorders,
    showOrthodromie,
    show_rivers,
    show_countriesNames,
    show_citiesNamesLevel,
    orthoLineWidth,
    orthoLineColor,
    scalePosX,
    scalePosY,
    f9map,
    f10map,
    f11map,
    f12map,

    speedLoss_On_TackReal,
    speedLoss_On_TackVlm,
    autoHideRoute,
    autoRemovePoiFromRoute,
    autoFillPoiHeading,
    routeSort_ByName,
    roadMap_interval,
    roadMap_HDG,
    roadMap_useInterval,

    autoConvertToRoute,
    angle_Range,
    angle_Step,
    timeStep_Less24,
    timeStep_More24,
    explo_New,
    use_RouteModule,
    use_Converge,
    check_Coast,
    check_Line,
    threshold_Alternative,
    nb_Alternative,
    visible_Only,
    auto_Zoom,
    autoZoom_Level,
    routage_MaxPres,
    routage_MaxPortant,
    routage_MaxWaveHeight,
    routage_MinPres,
    routage_MinPortant,
    routage_PruneWake,
    routage_Ortho,
    routage_ShowBestLive,
    routage_ColorGrib,
    routage_ShowIso,
    convertAndSimplify,

    showFlag,
    hideRoute,
    showNight,
    showScale,
    showPolar,
    showCompass,
    hideOpponent,
    hidePorte,
    hidePoi,
    hideLabel,
    hideBarrierSet,
    hideTrace,

    unitsPosition,
    unitsDistance,
    unitsLongitude,
    unitsLatitude,
    unitsTemp,

    httpProxyHostname,
    httpProxyPort,
    httpProxyUsername,
    httpProxyUserPassword,
    httpUseProxy,

    deviceType,
    gpsFake_fileName,
    gpsSerial_portName,
    gpsDerial_baudRate,

    kapAlpha,
    kapGribAlpha,
    kapDrawGrib,
    kapGribColored,
    LastKap,

    SETTING_MAX
};

#endif // SETTINGS_DEF_H
