######################################################################
# Automatically generated by qmake (2.01a) jeu. janv. 21 18:15:18 2010
######################################################################

TEMPLATE=lib
TARGET=clib
CONFIG+=staticlib
INCLUDEPATH += .

QMAKE_CLEAN += libclib.a
QMAKE_CFLAGS_RELEASE += -std=gnu99 -fno-stack-protector -pedantic

# Input
HEADERS += defs.h wind.h
SOURCES += wind.c
